export const SET_GAME_STARTED = 'SET_GAME_STARTED';
export const SET_INSTRUCTIONS_EXPANDED = 'SET_INSTRUCTIONS_EXPANDED';
export const GUESS = {
  SET_GUESS: 'SET_GUESS',
  SET_GUESS_SUITS: 'SET_GUESS_SUITS'
}

export const DECK = {
  FETCH_SUCCESS: 'DECK_FETCH_SUCCESS',
  FETCH_ERROR: 'DECK_FETCH_ERROR'
};

export const DECK_DRAW = {
  FETCH_SUCCESS: 'DECK_DRAW_FETCH_SUCCESS',
  FETCH_ERROR: 'DECK_DRAW_FETCH_ERROR'
}